---
title: "Tris_pH_slope"
author: "Micaela Chapuis"
date: "2025-02-18"
output: html_document
---

## Tris Calibration of pH using an Orion Multiparameter probe measuring mV, temperature, and salinity
## from Silbiger Lab (https://github.com/SilbigerLab/Protocols/blob/master/Probe_and_Logger_Protocols/Orion_Multiparameter_Sensor/Scripts/Tris_pH_Slope.R)

```{r}
rm(list=ls())
```

```{r}
library(tidyverse)
library(here)
library(seacarb)
library(broom)
```

Bring in pH calibration files and raw data files
```{r}
pHcalib<-read_csv(here("Test Sampling", "Data", "tris_calibration.csv"))
pHData<-read_csv(here("Test Sampling", "Data", "tidepool_chemistry.csv"))
```

Take the mV calibration files by each date and use them to calculate pH
```{r}
pHSlope <- pHcalib %>% 
  
            nest_by(date)%>%
            mutate(fitpH = list(lm(mVTris~TTris, data = pHcalib))) %>% # linear regression of mV and temp of the tris
            reframe(broom::tidy(fitpH)) %>% # make the output tidy
  
            select(date, term, estimate) %>%
            pivot_wider(names_from = term, values_from = estimate) %>% # put slope and intercept in their own column
  
            left_join(.,pHData) %>% # join with the pH sample data
  
            mutate(mVTris = temp_field*TTris + `(Intercept)`) %>% # calculate the mV of the tris at temperature in which the pH of samples were measured
  
           #drop_na() %>%       # Mica: commented out because I have a lot of NAs in data and this drops all no matter the column, will eventually use this again
  
            mutate(pH = pH(Ex=mV,Etris=mVTris,S=salinity_lab,T=temp_field)) %>% # calculate pH of the samples using the pH seacarb function
  
  #mutate(pH_insitu = pHinsi(pH = pH, ALK = TA_Raw, Tinsi = TempInSitu, Tlab = Temp, S = Salinity_lab_Silbiger)) %>%
  # Mica: this was already commented out 
  
            select(date, sample_ID,pH) # selects just these columns 
                # Mica: this used to also select Salinity_lab and TempInSitu but I chose to delete it because I will join back with the other data anyways

```


or if the above doesn't work
```{r}
#pHSlope<-pHcalib %>%
#  group_by(date)%>%
#  do(fitpH = lm(mVTris~TTris, data = .))%>% # linear regression of mV and temp of the tris
#  tidy(fitpH) %>% # make the output tidy
#  select(date, term, estimate) %>%
#  pivot_wider(names_from = term, values_from = estimate) %>%# put slope and intercept in their own column
#  left_join(.,pHData) %>% # join with the pH sample data
#  mutate(mVTris = TempInSitu*TTris + `(Intercept)`) %>% # calculate the mV of the tris at temperature in which the pH of samples were measured
#  drop_na() %>%
#  mutate(pH = pH(Ex=mV,Etris=mVTris,S=Salinity_lab,T=TempInSitu)) %>% # calculate pH of the samples using the pH seacarb function
#  #mutate(pH_insitu = pHinsi(pH = pH, ALK = TA_Raw, Tinsi = TempInSitu, Tlab = Temp, S = Salinity_lab_Silbiger)) %>%
#  select(date, SampleID,Salinity_lab,pH, TempInSitu) ## need to calculate pH insi then it is done
```


```{r}
View(pHSlope)
```


Write the data
```{r}
write_csv(pHSlope, here("Test Sampling", "Data", "pHSlope.csv"))
```

