---
title: "community_composition"
author: "Micaela Chapuis"
date: "2025-03-25"
output: github_document
---

## Load Libraries
```{r message = FALSE}
library(tidyverse)
library(here)
```

## Load in Data
```{r, message = FALSE}
prods <- read_csv(here("Test Sampling", "Data", "producers.csv"))
cons <- read_csv(here("Test Sampling", "Data", "consumers.csv"))
```


## Producers
```{r}
prods_long <- prods %>%
  select(-c("rock_sand_cover":"notes")) %>%
  pivot_longer(
    cols = c("rock_sand":"sponge"),
    names_to = "id",
    values_to = "num_points")
```


```{r}
prods_long %>% ggplot(aes(x= factor(pool_ID),
               y = num_points, 
               fill= factor(id), 
               color= id)) + # set lines surrounding each color to match the fill colors 
      geom_bar(stat="identity", position="fill") + # stacked bars
      facet_wrap(~substrate, scales = "free_x",
                 labeller = as_labeller(c(basalt = "Basalt", limestone = "Limestone"))) + 
  
      labs(x = "Pool", # labels
           y="Relative Abundance",
           fill = "Category") +

      theme_minimal() +  # theme
      theme(title = element_text(size = 18, face = "bold"), # make title bigger and bold
            axis.title = element_text(size = 16), # make all text bigger
            axis.text = element_text(size = 14),
            legend.title = element_text(size = 16),
            legend.text = element_text(size = 14)) +
    
      
      guides(color = "none") #+ # keep only legend for fill since fill and color are the same
      
#      scale_fill_manual(values = c('#e6194b', '#3cb44b', "lightblue", '#4363d8', '#f58231', '#000075', '#46f0f0', '#f032e6', '#fabebe', '#800000', '#008080',  '#e6beff', '#aaffc3', '#ffe119' , '#808000')) +
      
#      scale_color_manual(values = c('#e6194b', '#3cb44b', "lightblue", '#4363d8', '#f58231', '#000075', '#46f0f0', '#f032e6', '#fabebe', '#800000', '#008080',  '#e6beff', '#aaffc3', '#ffe119' , '#808000'))
```

```{r}
prods_cover_long <- prods %>%
  select(-c("rock_sand":"total_points", "cover_sum", "notes")) %>%
  pivot_longer(
    cols = c("rock_sand_cover":"slime_cover"),
    names_to = "id",
    values_to = "num_points")
```


```{r}
prods_cover_long %>% ggplot(aes(x= factor(pool_ID),
               y = num_points, 
               fill= factor(id), 
               color= id)) + # set lines surrounding each color to match the fill colors
      geom_bar(stat="identity", position="fill") + # stacked bars
      facet_wrap(~substrate, scales = "free_x") +
  
      labs(x = "Pool", # labels
           y="Relative Abundance",
           fill = "Category") +

      theme_minimal() +  # theme
      theme(title = element_text(size = 18, face = "bold"), # make title bigger and bold
            axis.title = element_text(size = 16), # make all text bigger
            axis.text = element_text(size = 14),
            legend.title = element_text(size = 16),
            legend.text = element_text(size = 14)) +
    
      
      guides(color = "none")  + # keep only legend for fill since fill and color are the same
      
      scale_fill_manual(values = c('#e6194b', '#ffe119', '#3cb44b', '#f58231', '#4363d8', '#aaffc3', "#7C4585")) +
      
      scale_color_manual(values = c('#e6194b', '#ffe119',  '#3cb44b', '#f58231', '#4363d8', '#aaffc3', "#7C4585"))
```


## Consumers
```{r}
cons %>% ggplot(aes(x = factor(pool_number),
                    y = consumer_density)) +
  geom_bar(stat = "identity") +
  facet_wrap(~substrate, scale = "free_x") 
```



```{r}
cons_long <- cons %>%
  select(-c("total_consumers":"notes")) %>%
  pivot_longer(
    cols = c("sea_hare":"jellyfish"),
    names_to = "id",
    values_to = "count")
```

```{r}
cons_long %>% ggplot(aes(x = factor(pool_ID),
                    y = count , 
                    fill = id)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~substrate, scale = "free_x")
```

```{r}
cons_long %>% ggplot(aes(x= factor(pool_ID),
               y = count, 
               fill= factor(id), 
               color= id)) + # set lines surrounding each color to match the fill colors
      geom_bar(stat="identity", position="fill") + # stacked bars
      facet_wrap(~substrate, scale = "free_x",
                 labeller = as_labeller(c(basalt = "Basalt", limestone = "Limestone"))) +
   
      labs(x = "Pool", # labels
           y="Relative Abundance",
           fill = "Category") +

      theme_minimal() +  # theme
      theme(title = element_text(size = 18, face = "bold"), # make title bigger and bold
            axis.title = element_text(size = 16), # make all text bigger
            axis.text = element_text(size = 14),
            legend.title = element_text(size = 16),
            legend.text = element_text(size = 14)) +
    
      
      guides(color = "none") + # keep only legend for fill since fill and color are the same
      
      scale_fill_manual(values = c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#000075', '#46f0f0', '#f032e6', '#aaffc3', "#7C4585", "#F8F8E1")) +
      
      scale_color_manual(values = c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#000075', '#46f0f0', '#f032e6', '#aaffc3', "#7C4585", "#F8F8E1"))
```

