---
title: "First Analysis"
author: "Micaela Chapuis"
date: "2025-02-25"
output: github_document
---

## Load Libraries
```{r}
library(tidyverse)
library(here)
library(seacarb)
```

## Load in Data
```{r, message = FALSE}
chem <- read_csv(here("Test Sampling", "Data", "tidepool_chemistry.csv"))
params <- read_csv(here("Test Sampling", "Data", "tidepool_parameters.csv"))
pHSlope <- read_csv(here("Test Sampling", "Data", "pHSlope.csv"))
TA_Sandy <- read_csv(here("Test Sampling", "Data", "TA", "TA_SB_20250216.csv"))
TA_DH <- read_csv(here("Test Sampling", "Data", "TA", "TA_DH_20250223.csv"))
```

## Data cleaning and joining

Make all pool numbers factors
```{r}
chem$pool_number <- factor(chem$pool_number)
params$pool_number <- factor(params$pool_number)
```


Remove junk samples from TA Data
```{r}
junks <- c("junk1", "junk2", "junk3")
TA_Sandy <- TA_Sandy %>% filter(!SampleID %in% junks)
TA_DH <- TA_DH %>% filter(!SampleID %in% junks)
```

Sandy TA data needs to have "sb_" added to the sample ID
```{r}
TA_Sandy$SampleID <- str_c("sb_", TA_Sandy$SampleID)
```


```{r}
colnames(TA_Sandy)[2] <- "TA1" # rename the column so I can later coalesce them together

data <- plyr::join_all(list(chem,(TA_Sandy %>% select(SampleID, TA1)),(TA_DH %>% select(SampleID, TA))), by='SampleID', type='left') # join all 3 dfs by sample ID. From the TA dfs pick which columns i want to keep

data$alkalinity <- coalesce(data$TA1, data$TA) # combine the TA1 (from sandy) and TA (from dh) into one alkalinity column
```


Add in pH calculated from tris and physical parameters
```{r}
data <- left_join(data, pHSlope)
data <- left_join(data, (params %>% select(date, site, pool_number, substrate, perimeter_m, surface_area_m2)))
```

Selecting columns 
```{r}
data <- data %>% select(-observers, -notes, -TA1, -TA)
```

Separating Sandy Beach and Diamond Head
```{r}
sandy_data <- data %>% filter(site %in% "Sandy Beach") 
dh_data <- data %>% filter(site %in% "Diamond Head")
```


## Data Viz!
### Sandy Beach
```{r}
sandy_data %>% ggplot(aes(x = time_point, y = temp_pool, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```


```{r}
sandy_data %>% ggplot(aes(x = time_point, y = pH, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```

```{r}
sandy_data %>% ggplot(aes(x = time_point, y = alkalinity, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```

```{r}
sandy_data %>% ggplot(aes(x = time_point, y = Salinity_lab, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```


### Diamond Head 
```{r}
dh_data %>% ggplot(aes(x = time_point, y = temp_pool, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```


```{r}
dh_data %>% ggplot(aes(x = time_point, y = pH, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```

```{r}
dh_data %>% ggplot(aes(x = time_point, y = alkalinity, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```

```{r}
dh_data %>% ggplot(aes(x = time_point, y = Salinity_lab, color = pool_number)) + geom_line() + geom_point() + theme_minimal()
```

